<?php

/**
 * Implements hook_library().
 */
function quick_edit_library() {
  $path = drupal_get_path('module', 'quick_edit');
  $options = array(
    'scope' => 'footer',
    'defer' => TRUE,
  );
  $libraries['quick-edit'] = array(
    'title' => 'Quick in-line editing',
    'version' => VERSION,
    'css' => array(
      $path . '/css/quick-edit.css',
    ),
    'js' => array(
      $path . '/js/quick-edit.js' => $options,
      $path . '/js/contextual.js' => $options,
    ),
    'dependencies' => array(
      array('system', 'jquery'),
      array('navbar', 'underscore'),
      array('navbar', 'backbone'),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_navbar().
 */
function quick_edit_navbar() {
  $items['quick_edit_navbar'] = array(
    '#type' => 'navbar_item',
    'tab' => array(
      'trigger' => array(
        '#title' => t('Quick Edit'),
        '#type' => 'link',
        '#href' => current_path(),
        '#options' => array('attributes' => array('id' => 'quick-edit-trigger-link')),
        '#attached' => array('library' => array(array('quick_edit', 'quick-edit'))),
        '#theme' => 'html_tag',
        '#tag' => 'button',
        '#value_prefix' => '<span class="element-invisible">',
        '#value_suffix' => '</span>',
        '#value' => t('Quick Edit'),
        '#attributes' => array(
          'class' => array('navbar-icon', 'navbar-icon-quick-edit'),
          'id' => 'quick-edit-trigger-link'
        ),
      ),
    ),
    '#wrapper_attributes' => array(
      'id' => 'quick-edit-navbar-tab',
      'class' => array('navbar-tab-quick-edit'),
    ),
    '#weight' => -999,
    '#access' => user_access('access in-place editing'),
  );
  return $items;
}

/**
 * Implements hook_js_alter().
 */
function quick_edit_js_alter(&$javascript) {
  unset($javascript['modules/contextual/contextual.js']);
}

